apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgresql-auto-failover.monitor.fullname" . }}
type: Opaque
data:
  autoctlNodePassword: "{{ .Values.monitor.autoctlNodePassword | b64enc }}"
