apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgresql-auto-failover.monitor.fullname" . }}-headless
  labels:
    {{- include "postgresql-auto-failover.monitor.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: postgresql
      port: 5432
      targetPort: postgresql
      protocol: TCP
  selector:
    {{- include "postgresql-auto-failover.monitor.selectorLabels" . | nindent 4 }}
