apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgresql-auto-failover.node.fullname" . }}
type: Opaque
data:
  pgAutoFailoverReplicatorPassword: "{{ .Values.node.pgAutoFailoverReplicatorPassword | b64enc }}"
  postgresPassword: "{{ .Values.node.postgresPassword | b64enc }}"
