apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "postgresql-auto-failover.node.fullname" . }}
  labels:
    {{- include "postgresql-auto-failover.node.labels" . | nindent 4 }}
data:
  node.sh: |+
    {{ .Files.Get "node.sh" | indent 4 | trim  }}

  postgresql.conf: |
    password_encryption = scram-sha-256
    hba_file = '/opt/configmap/pg_hba.conf'

  custom-postgresql.conf: |
    {{ .Values.node.postgresqlConfiguration | indent 4 | trim }}

  pg_hba.conf: |
    {{ .Values.node.pgHbaConfiguration | indent 4 | trim }}
