apiVersion: v2
name: pg-auto-failover
description: A Helm chart for PostgreSQL with pg_auto_failover

type: application

version: 0.1.2

appVersion: 12-1.4

keywords:
  - postgres
  - postgresql
  - pg_auto_failover
